# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170820_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.County', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Area', verbose_name='Okręg'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Nazwa'),
        ),
    ]
