# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170820_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='District',
        ),
        migrations.RenameModel(
            old_name='County',
            new_name='Voivodeship',
        ),
        migrations.RenameField(
            model_name='commune',
            old_name='area',
            new_name='district',
        ),
    ]
