# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170821_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Nazwa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='voivodeship',
            name='country',
            field=models.ForeignKey(default='Polska', on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='Kraj'),
            preserve_default=False,
        ),
    ]
