# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170820_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='county',
            new_name='voivodeship',
        ),
    ]
