# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='county',
            field=models.ForeignKey(default='MAZOWIECKIE', on_delete=django.db.models.deletion.CASCADE, to='main.County'),
            preserve_default=False,
        ),
    ]
