# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_commune_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='cards',
            field=models.IntegerField(verbose_name='Karty wydane'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='grabowski',
            field=models.IntegerField(verbose_name='Dariusz Maciej GRABOWSKI'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='ikonowicz',
            field=models.IntegerField(verbose_name='Piotr IKONOWICZ'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='invalid',
            field=models.IntegerField(verbose_name='Głosy nieważne'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='kalinowski',
            field=models.IntegerField(verbose_name='Jarosław KALINOWSKI'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='korwin',
            field=models.IntegerField(verbose_name='Janusz KORWIN-MIKKE'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='krzaklewski',
            field=models.IntegerField(verbose_name='Marian KRZAKLEWSKI'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='kwasniewski',
            field=models.IntegerField(verbose_name='Aleksander KWAŚNIEWSKI'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='lepper',
            field=models.IntegerField(verbose_name='Andrzej LEPPER'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='lopuszanski',
            field=models.IntegerField(verbose_name='Jan ŁOPUSZAŃSKI'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='olechowski',
            field=models.IntegerField(verbose_name='Andrzej Marian OLECHOWSKI'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='pawlowski',
            field=models.IntegerField(verbose_name='Bogdan PAWŁOWSKI'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='people',
            field=models.IntegerField(verbose_name='Uprawnieni'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='subareas',
            field=models.IntegerField(verbose_name='Obwody'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='walesa',
            field=models.IntegerField(verbose_name='Lech Wałęsa'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='wilecki',
            field=models.IntegerField(verbose_name='Tadeusz Adam WILECKI'),
        ),
    ]
